  
  <?php if(getdate()['mon']==1){ ?>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
<?php }elseif(getdate()['mon']==2){  ?>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
<?php }elseif(getdate()['mon']==3){  ?>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
<?php }elseif(getdate()['mon']==4){  ?>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
<?php }elseif(getdate()['mon']==5){  ?>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
<?php }elseif(getdate()['mon']==6){  ?>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
<?php }elseif(getdate()['mon']==7){  ?>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
<?php }elseif(getdate()['mon']==8){  ?>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
<?php }elseif(getdate()['mon']==9){  ?>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
<?php }elseif(getdate()['mon']==10){  ?>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
<?php }elseif(getdate()['mon']==11){  ?>
    <span id="current-month">Tháng 11</span>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
<?php }elseif(getdate()['mon']==12){  ?>
    <span id="current-month">Tháng 12</span>
    <span id="current-month">Tháng 1</span>
    <span id="current-month">Tháng 2</span>
    <span id="current-month">Tháng 3</span>
    <span id="current-month">Tháng 4</span>
    <span id="current-month">Tháng 5</span>
    <span id="current-month">Tháng 6</span>
    <span id="current-month">Tháng 7</span>
    <span id="current-month">Tháng 8</span>
    <span id="current-month">Tháng 9</span>
    <span id="current-month">Tháng 10</span>
    <span id="current-month">Tháng 11</span>
<?php } ?>


                   