<?php 
//include('model/historicalsite.php');
include('model/governanceAgency.php');
include('model/festival.php');
include('model/tour.php');
include('model/craftvillage.php');
include('model/restaurant.php');
include('model/hotel.php');
include('model/image360.php');
include('model/event.php');
?>
