<?php 
include('model/governanceAgency.php');
include('model/festival.php');
include('model/tour.php');
include('model/craftvillage.php');
include('model/restaurant.php');
include('model/hotel.php');
include('model/image360.php');
include('model/event.php');
include('model/like.php');
include('model/place.php');
include('model/service.php');
include('model/eventcenter.php');
include('model/booktable.php');
include('model/booktour.php');
include('model/bookhotel.php');
include('model/report.php');
include('model/historicalsite.php');
?> 