<?php 
include('model/products.php');
include('model/orders.php');
include('model/order_details.php');
include('model/discount_code.php');
include('model/question.php');
include('model/evaluates.php');
include('model/views.php');
include('model/reviews.php');
include('model/categorie_product.php');
include('model/address.php');
include('model/unit_conversion.php');
?>