<?php 
global $sqlInstallDatabase;
global $sqlDeleteDatabase;

$sqlInstallDatabase = 'CREATE TABLE `members` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `avatar` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `phone` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `email` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `password` TEXT NULL , `status` INT NOT NULL , `type` INT NOT NULL , `id_member` INT NULL DEFAULT NULL , `created_at` DATETIME NULL DEFAULT NULL , `updated_at` DATETIME NULL DEFAULT NULL , `last_login` DATETIME NULL DEFAULT NULL , `dateline_at` DATETIME NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;';

$sqlInstallDatabase .= "CREATE TABLE `products` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL , `id_category` INT NOT NULL , `hot` BOOLEAN NOT NULL , `description` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL , `keyword` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL , `info` TEXT CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL , `image` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL , `code` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL , `price` INT NOT NULL , `price_old` INT NOT NULL , `quantity` INT NOT NULL , `id_manufacturer` INT NOT NULL , `status` VARCHAR(255) NOT NULL , `slug` VARCHAR(255) NOT NULL , `view` INT NOT NULL DEFAULT '0' , PRIMARY KEY (`id`)) ENGINE = InnoDB; ";
$sqlDeleteDatabase = '';

$sqlInstallDatabase .= "CREATE TABLE `spas` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT NOT NULL , `phone` TEXT NULL DEFAULT NULL , `email` TEXT NULL DEFAULT NULL , `id_member` INT NOT NULL , `address` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `note` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `image` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `slug` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `created_at` DATETIME NOT NULL , `updated_at` DATETIME NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .="CREATE TABLE `trademarks` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `created_at` DATETIME NULL DEFAULT NULL , `updated_at` DATETIME NULL DEFAULT NULL , `id_member` INT NOT NULL , `image` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `slug` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .="CREATE TABLE `warehouses` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT NOT NULL , `description` TEXT NULL DEFAULT NULL , `created_at` INT NULL DEFAULT NULL , `credit` INT NULL DEFAULT NULL , `id_member` INT NOT NULL , `id_spa` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .="CREATE TABLE `customers` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL  , `phone` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL  , `email` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL  , `address` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL  , `sex` BOOLEAN NOT NULL , `id_city` TINYINT NOT NULL , `id_messenger` VARCHAR(255) NOT NULL, `avatar` TEXT NOT NULL, `status` VARCHAR(255) NOT NULL , `pass` VARCHAR(255) NOT NULL , `id_parent` INT NOT NULL DEFAULT '0' , `id_level` INT NOT NULL DEFAULT '0' , `birthday_date` INT NOT NULL , `birthday_month` INT NOT NULL , `birthday_year` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .= "CREATE TABLE `customer_group` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `created_at` DATETIME NULL DEFAULT NULL , `note` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `id_member` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .= "CREATE TABLE `services` ( `id` INT NOT NULL , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `code` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `id_category` INT NOT NULL , `id_member` INT NOT NULL , `id_spa` INT NULL DEFAULT NULL , `price` INT NULL DEFAULT NULL , `price_old` INT NULL DEFAULT NULL , `image` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `created_at` DATETIME NULL DEFAULT NULL , `updated_at` DATETIME NULL DEFAULT NULL , `duration` INT NULL DEFAULT NULL COMMENT 'thời lương ' , `hot` INT NULL DEFAULT NULL ) ENGINE = InnoDB;";

$sqlInstallDatabase .= "CREATE TABLE `rooms` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `created_at` DATETIME NULL DEFAULT NULL , `status` INT NULL DEFAULT NULL , `id_member` INT NOT NULL , `id_spa` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .="CREATE TABLE `quayso_spa`.`beds` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `created_at` DATETIME NOT NULL , `status` INT NOT NULL , `id_member` INT NOT NULL , `id_spa` INT NOT NULL , `id_room` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";

$sqlInstallDatabase .="CREATE TABLE `combos` ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `service` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `product` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `price` INT NULL DEFAULT NULL , `discount` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `total_price` INT NULL DEFAULT NULL , `description` TEXT NULL DEFAULT NULL , `status` INT NULL DEFAULT NULL , `created_at` DATETIME NOT NULL , `updated_at` DATETIME NOT NULL , `quantity` INT NULL DEFAULT NULL , `id_member` INT NOT NULL , `id_spa` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
";
$sqlInstallDatabase .="CREATE TABLE ( `id` INT NOT NULL AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL , `phone` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `email` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `id_member` INT NOT NULL , `id_group` INT NOT NULL , `id_spa` INT NULL DEFAULT NULL, `id_customers` INT NOT NULL , `id_services` INT NOT NULL , `created_at` DATETIME NOT NULL , `created_orders` DATETIME NOT NULL , `id_staff` INT NULL DEFAULT NULL , `type` TEXT NULL DEFAULT NULL COMMENT 'kiểu đặt (1 Mặc định, 2, Lịch chăm sóc, 3 Lịch liệu trình, 4Lịch điều trị)' , `status` TINYINT NULL DEFAULT NULL COMMENT '0: Chưa xác nhận, 1: Xác nhận, 2:Không đến, 3:Hủy, 4:Đã đến , 5:Đặt online.' , `note` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `apt_step` INT NULL DEFAULT NULL , `apt_times` INT NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;";
$sqlInstallDatabase .="CREATE TABLE `prepay_cards` ( `id` INT NOT NULL  AUTO_INCREMENT , `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL , `price` INT NULL DEFAULT NULL , `discount_money` INT NULL DEFAULT NULL , `total_price` INT NULL DEFAULT NULL , `special_price_momo` INT NULL DEFAULT NULL , `note` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL , `use_time` INT NULL DEFAULT NULL , `id_member` INT NOT NULL , `id_spa` INT NOT NULL , `status` TINYINT NOT NULL, PRIMARY KEY (`id`)) ENGINE = InnoDB;";
/*
$sqlDeleteDatabase .= "DROP TABLE lessons; ";
$sqlDeleteDatabase .= "DROP TABLE historytests; ";
$sqlDeleteDatabase .= "DROP TABLE tests; ";
$sqlDeleteDatabase .= "DROP TABLE questions; ";

$sqlDeleteDatabase .= "DELETE FROM `categories` WHERE `type`='2top_crm_training'; ";
$sqlDeleteDatabase .= "DELETE FROM `options` WHERE `key_word`='settingTraining2TOPCRM'; ";
*/
?>