<?php

include('model/agencies.php');
include('model/agency_accounts.php');
include('model/agency_orders.php');
include('model/products.php');
include('model/combo_products.php');
include('model/combos.php');
include('model/users.php');
include('model/agency_order_details.php');
include('model/user_orders.php');
include('model/user_order_details.php');
include('model/agency_products.php');
include('model/agency_combos.php');
include('model/agency_order_histories.php');
include('model/user_combo_orders.php');
include('model/user_combo_order_details.php');
include('model/user_order_combo_histories.php');
include('model/user_order_histories.php');
include('model/agency_order_back_stores.php');
include('model/agency_order_back_store_details.php');
include('model/agency_order_back_store_histories.php');
include('model/agency_order_products.php');
include('model/agency_order_product_details.php');
include('model/agency_order_product_histories.php');
