<?php
include('model/provinces.php');
include('model/users.php');
include('model/bookings.php');
include('model/pinned_provinces.php');
include('model/booking_fees.php');
include('model/images.php');
include('model/driver_requests.php');
include('model/withdraw_requests.php');
include('model/transactions.php');
include('model/complaints.php');
include('model/notifications.php');
include('model/user_bookings.php');
include('model/support_requests.php');
include('model/booking_deals.php');
include('model/canceled_booking_requests.php');
include('model/bookmarks.php');
include('model/block_user_provinces.php');
include('model/reward.php');
?>