$(document).ready(function(){$('.tab-account a').click(function(){var tab_id=$(this).attr('data-tab');$('.tab-account a').removeClass('active');$('.tab-content').removeClass('active');$(this).addClass('active');$("#"+tab_id).addClass('active');});setTimeout(function(){$('.loading').addClass('active');},3500);$('.clc-forgot').click(function(){$('.step-1').addClass('active');});$('.back-step a').click(function(){$(this).closest('.step-forgot').removeClass('active');});$('.item-method').click(function(){$('.item-method').removeClass('active');$(this).addClass('active');});var clicked=0;$(".show-pass").click(function(e){e.preventDefault();if(clicked==0){clicked=1;}else{clicked=0;}
var input=$($(this).attr("toggle"));if(input.attr("type")=="password"){input.attr("type","text");}else{input.attr("type","password");}});(function($){$.fn.countdown=function(milliseconds,callback){$('.sendotpnew').addClass('d-none');var $el=this;var end,timer;milliseconds=milliseconds||60;end=new Date(Date.now()+milliseconds);tick();function formatTime(time){seconds=time.getSeconds();return seconds;}
function tick(){var remaining=new Date(end-Date.now());if(remaining>0){$el.html(formatTime(remaining));timer=setTimeout(tick,1000);}else{clearInterval(timer);$('.countdowntime').addClass('d-none');$('.sendotpnew').removeClass('d-none');if(callback)callback.apply($el);}};};$('#timer').countdown(60*1000);})(jQuery);$('.slide-banner').slick({autoplay:false,arrow:false,slidesToShow:1,slidesToScroll:1,dots:false,prevArrow:'',nextArrow:'',});$('.slide-avarta').slick({autoplay:false,arrow:false,slidesToShow:2.2,dots:false,infinite:false,prevArrow:'',nextArrow:'',});$('.slide-product').slick({autoplay:false,arrow:false,slidesToShow:2,dots:false,prevArrow:'',nextArrow:'',});$('.info-confirm a').click(function(){$('.info-confirm').slideUp(400);$('.content-thumb-info').slideDown(400);});$('.tu-lieu').click(function(){$('.clc-back').removeClass('active');$('.box-detail-product, .back-data, .avarta-user').addClass('active');});$('.back-data').click(function(){$('.box-detail-product, .clc-back').removeClass('active');$('.back-home, .back-temp').click();});$('.btn-back-card').click(function(){$('.home-card, .home-card-box, .box-password, .btn-back-card, .user-card, .btn-back-card-home').removeClass('active');});$('.user-card p svg').click(function(){$('.hide-mn, .numb-mn').toggleClass('active');$(this).toggleClass('active');});$('.clc-checkout').click(function(){$('.box-data-pol, .clc-back, .avarta-user').removeClass('active');$('.box-money, html, body').addClass('active');$('.home-card-box, .btn-back-card, .btn-back-card-home').addClass('active');});$('.recharge').click(function(){$('.home-card-box, .btn-back-card, .btn-back-card-home').addClass('active');});$('.btn-back-card-home').click(function(){$('.box-money, html, body').removeClass('active');});$('.clc-detail-temp').click(function(){$('.box-detail-template, .avarta-user, .back-temp, html, body').addClass('active');});$('.back-temp').click(function(){$('.box-detail-template, .avarta-user, .back-temp, html, body').removeClass('active');});$('.clc_layer').click(function(){$('.clc_layer').removeClass('active')
$(this).addClass('active');});$('.layer-1').click(function(){$('.active-event').slideDown(300);$('.active-setting').slideUp(300);$('.info-txt-tb').slideUp(300);});$('.layer-2').click(function(){$('.active-setting').slideDown(300);$('.info-txt-tb').slideUp(300);$('.active-event').slideUp(300);});$('.back-layer').click(function(){$('.box-detail-edit-buy, .clc-back, .box-detail-create, .box-detail-product, html, body, .avarta-user').removeClass('active');})
$('.clc-back').click(function(){$('.menu-bottom').removeClass('active');})
$('.open_account').click(function(){$('.box-account, html').addClass('active');})
$('.back-home').click(function(){$('.box-account, html').removeClass('active');})
function resizeCanvases(){[].forEach.call(document.querySelectorAll(".rainbow-pixel-canvas"),function(canvas){canvas.width=document.body.clientWidth;canvas.height=window.innerHeight*0.7;});}
$(document).ready(function(){function rangeSlider(){let slider=document.querySelectorAll(".range-slider");let range=document.querySelectorAll(".range-slider__range");let value=document.querySelectorAll(".range-slider__value");slider.forEach((activeSlider)=>{value.forEach((activeValue)=>{let val=activeValue.previousElementSibling.getAttribute("value");activeValue.innerText=val;});range.forEach((elem)=>{elem.addEventListener("input",(eventArgs)=>{let lass=eventArgs.target.getAttribute("data-class");elem.nextElementSibling.innerText=eventArgs.target.value;$('.'+lass).val(eventArgs.target.value);});});});}
rangeSlider();$(".clc-close-action").click(function(){$(".clc-action-edit").removeClass("active");$(".content-action").removeClass("active");});$(".clc-action-edit").click(function(){var tab_id=$(this).attr("data-tab");$(this).addClass("active");$("#"+tab_id).addClass("active");});});})