<?php
include('model/users.php');
include('model/courses.php'); 
include('model/lessons.php'); 
include('model/tests.php'); 
include('model/questions.php'); 
include('model/historytests.php'); 
include('model/fasting.php'); 
include('model/price_lists.php'); 
include('model/challenges.php'); 
?>