<?php
include('model/users.php');
include('model/courses.php'); 
include('model/lessons.php'); 
include('model/tests.php'); 
include('model/questions.php'); 
include('model/historytests.php'); 
include('model/fasting.php'); 
include('model/price_lists.php'); 
include('model/challenges.php'); 
include('model/feedback_challenges.php'); 
include('model/result_challenges.php'); 
include('model/tip_challenges.php'); 
include('model/contact.php');
include('model/coach.php');
include('model/transactions.php');
include('model/user_challenges.php');
include('model/user_courses.php');
include('model/workout.php');
include('model/exercise_workouts.php');
include('model/answerquestion.php');
?>